name: generate_products_action
description: Action to generate pi-gen images for a specific target OS. (only run this with a container image)

inputs:
  # Actions cannot access secrets so pass them in as inputs
  pi_release:
    required: true
    description: The pi release to use to get the debian release
  pi_arch:
    required: true
    description: The pi arch to use to get the debian release (e.g. armhf or arm64)
  github_token:
    required: true
    description: The GitHub token to use for accessing the repository
  compare_file0:
    required: true
    description: The file to compare the generated files
  compare_file1:
    required: true
    description: The file to compare the generated files
  repository:
    required: false
    description: The repository to save the cache
    default: ${{ github.repository }}

runs:
  using: "composite"
  steps:
    - name: Check inputs
      shell: bash
      run: |
        [[ "${{ inputs.pi_release }}"    ]] || { echo "pi_release input is empty"    ; exit 1; }
        [[ "${{ inputs.pi_arch }}"       ]] || { echo "pi_arch input is empty"       ; exit 1; }
        [[ "${{ inputs.github_token }}"  ]] || { echo "github_token input is empty"  ; exit 1; }
        [[ "${{ inputs.compare_file0 }}" ]] || { echo "compare_file0 input is empty" ; exit 1; }
        [[ "${{ inputs.compare_file1 }}" ]] || { echo "compare_file1 input is empty" ; exit 1; }
        [[ "${{ inputs.repository }}"    ]] || { echo "repository input is empty"    ; exit 1; }

    - name: sleep
      shell: sh
      run: |
        SLEEP="$((1 + $(od -A n -t d -N 2 /dev/urandom | tr -d ' ') % 9))"
        echo "Sleeping $SLEEP seconds ..."
        sleep $SLEEP

    - name: env
      id: env
      shell: bash
      run: |
        export KEY="${GITHUB_WORKFLOW%-*}"
        echo "key=$KEY" >> $GITHUB_OUTPUT
        echo "################################################################" && bash -c "echo KEY=$KEY"

        export RELEASE="${{ inputs.pi_release }}"
        echo "release=$RELEASE" >> $GITHUB_OUTPUT
        echo "################################################################" && bash -c "echo RELEASE=$RELEASE"

        export ARCH="${{ inputs.pi_arch }}"
        echo "arch=$ARCH" >> $GITHUB_OUTPUT
        echo "################################################################" && bash -c "echo ARCH=$ARCH"

        export TIMESTAMP="$(date -u +%Y%m%d_%H%M%S)"
        echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
        echo "################################################################" && bash -c "echo TIMESTAMP=$TIMESTAMP"

        echo "keymatrix=$KEY-$RELEASE-$ARCH" >> $GITHUB_OUTPUT

    - name: update
      shell: bash
      run: apt-get -y update && apt-get -y upgrade && apt-get -y dist-upgrade

    - name: install
      env:
        DEBIAN_FRONTEND: noninteractive
      shell: bash
      run: |
        apt-get -y install \
          git vim parted \
          quilt coreutils qemu-user-static debootstrap zerofree zip dosfstools e2fsprogs \
          libarchive-tools libcap2-bin rsync grep udev xz-utils curl xxd file kmod bc \
          binfmt-support ca-certificates qemu-utils kpartx fdisk gpg pigz arch-test \
        && rm -rf /var/lib/apt/lists/*

    - name: cache_load
      uses: actions/cache/restore@v5
      with:
        path: |
          ${{ inputs.compare_file0 }}
        key: ${{ steps.env.outputs.keymatrix }}-${{ steps.env.outputs.timestamp }}
        restore-keys: |
          ${{ steps.env.outputs.keymatrix }}-

    - name: prepare before clone
      id: prepare-before-clone
      shell: bash
      env:
        PIGEN_READING_FILE: raw/refs/heads/master/build.sh
        PIGEN_REPOSITORY: RPi-Distro/pi-gen
      run: |
        LATEST_DEBIAN_RELEASE=$(curl -fsSL ${GITHUB_SERVER_URL##*/}/${PIGEN_REPOSITORY}/${PIGEN_READING_FILE} | grep -oP '(?<=\{RELEASE:-)[^}]+')

        if [[ "${{ inputs.pi_release }}" = "${LATEST_DEBIAN_RELEASE}" ]]; then
          if [[ "${{ inputs.pi_arch }}" = "arm64" ]]; then
            PIGEN_BRANCH="arm64"
          else
            PIGEN_BRANCH="master"
          fi
        else
          if [[ "${{ inputs.pi_arch }}" = "arm64" ]]; then
            PIGEN_BRANCH="${{ inputs.pi_release }}-arm64"
          else
            PIGEN_BRANCH="${{ inputs.pi_release }}"
          fi
        fi

        echo "pigen_repository=$PIGEN_REPOSITORY" >> $GITHUB_OUTPUT
        echo "pigen_branch=$PIGEN_BRANCH"         >> $GITHUB_OUTPUT

    - name: compare
      shell: bash
      id: compare
      run: |
        git ls-remote https://github.com/${{ steps.prepare-before-clone.outputs.pigen_repository }} -b ${{ steps.prepare-before-clone.outputs.pigen_branch }} HEAD | cut -f1 | tail -n1 > ${{ inputs.compare_file1 }}

        if [ ! -e "${{ inputs.compare_file0 }}" ]; then
          echo "copy File for cache"
          cp ${{ inputs.compare_file1 }} ${{ inputs.compare_file0 }}
        else
          CONTENT_FILE0=$(cat ${{ inputs.compare_file0 }})
          CONTENT_FILE1=$(cat ${{ inputs.compare_file1 }})
          if [ "$CONTENT_FILE0" = "$CONTENT_FILE1" ]; then
            echo "Still at latest version"
            echo "latest_version=true" >> $GITHUB_OUTPUT
          else
            echo "Not at latest version"
            cp ${{ inputs.compare_file1 }} ${{ inputs.compare_file0 }}
          fi
        fi

    - name: clone
      if: steps.compare.outputs.latest_version != 'true'
      uses: actions/checkout@v6
      with:
        token: ${{ inputs.github_token }}
        repository: ${{ steps.prepare-before-clone.outputs.pigen_repository }}
        ref: ${{ steps.prepare-before-clone.outputs.pigen_branch }}        

    - name: prepare
      shell: bash
      if: steps.compare.outputs.latest_version != 'true'
      run: |
        # disable full build stage
        touch ./stage5/SKIP
        touch ./stage5/SKIP_IMAGES
        # create config
        touch config
        echo IMG_NAME=raspios-${{ inputs.pi_release }}-${{ inputs.pi_arch }} >> config
        echo RELEASE=${{ inputs.pi_release }}                                >> config
        echo DEPLOY_COMPRESSION=xz                                           >> config

    - name: generate
      shell: bash
      if: steps.compare.outputs.latest_version != 'true'
      run: |
        ./build.sh

    - name: after prepare
      shell: bash
      if: steps.compare.outputs.latest_version != 'true'
      run: |
        # split bigger files
        cd ./deploy
        for file in *.img.xz; do
          if [[ -f "$file" ]]; then
            size=$(stat -c %s "$file")
            if (( size > 1920*1024*1024 )); then
              echo "Processing $file (size: $size bytes > 1920MB)"
              split -b 1920M --numeric-suffixes=1 --suffix-length=3 "$file" "$file."
              rm "$file"
            else
              echo "$file is smaller than 1920 MB, splitting is skipped."
            fi
          fi
        done

    - name: Delete existing tag
      if: steps.compare.outputs.latest_version != 'true'
      uses: dev-drprasad/delete-tag-and-release@v1.1
      continue-on-error: true
      with:
        tag_name: "${{ inputs.pi_arch }}-${{ inputs.pi_release }}"
        github_token: ${{ inputs.github_token }}
        delete_release: true
        repo: ${{ inputs.repository }}

    - name: Publish release files
      if: steps.compare.outputs.latest_version != 'true'
      uses: softprops/action-gh-release@v2
      with:
        token: "${{ inputs.github_token }}"
        tag_name: "${{ inputs.pi_arch }}-${{ inputs.pi_release }}"
        generate_release_notes: false
        prerelease: false
        draft: false
        name: "rpi image for ${{ inputs.pi_arch }}-${{ inputs.pi_release }}"
        files: |
          ./deploy/*
        body: |
          ### ${{ inputs.pi_arch }} rpi image for ${{ inputs.pi_arch }}-${{ inputs.pi_release }}
          - This package was generated by the pi-gen GitHub Action.
          - The files are downloadable in the Assets.
          - For more information, see the [README.md in the repository](https://github.com/${{ inputs.repository }}/blob/${{ github.ref }}/README.md).

    - name: cache_save
      if: steps.compare.outputs.latest_version != 'true'
      uses: actions/cache/save@v5
      with:
        path: |
          ${{ inputs.compare_file0 }}
        key: ${{ steps.env.outputs.keymatrix }}-${{ steps.env.outputs.timestamp }}
