name: generate_products

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/generate_products.yml'
      - '.github/actions/pi-gen/**'
  schedule:
    - cron: '34 14 */3 * 2'
  workflow_dispatch:
    inputs:
      build_armhf:
        description: 'Build armhf-Packages?'
        required: true
        options: [ 'yes', 'no' ]
        type: choice
        default: 'yes'
      build_arm64:
        description: 'Build arm64-Packages?'
        required: true
        options: [ 'yes', 'no' ]
        type: choice
        default: 'yes'
      recache:
        description: 'Delete Cache before Build?'
        required: false
        options: [ 'yes', 'no' ]
        type: choice
        default: 'no'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  COMPARE_FILE0: /tmp/.compare-0.txt
  COMPARE_FILE1: /tmp/.compare-1.txt

jobs:

  clear_cache:
    runs-on: ubuntu-latest
    steps:
      - name: clear_cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_ONWER: ${{ github.repository_owner }}
          GH_REPO: ${{ github.event.repository.name }}
        shell: bash
        run: |
          set -e +o pipefail
          if [ "${{ github.event.inputs.recache }}" == "yes" ]; then
            echo "Recache selected - Deleting all caches for this workflow ..."
            while :; do
                JSON_OUTPUT=$(curl \
                    -H "Accept: application/vnd.github.v3+json" \
                    -H "Authorization: token $GH_TOKEN" \
                    https://api.github.com/repos/$GH_ONWER/$GH_REPO/actions/caches)
                GH_CACHE_IDS=$(echo "$JSON_OUTPUT" | jq '.actions_caches[] | {id: .id}' | grep "id" | cut -d ':' -f 2 | cut -c 2-)
                if [ -z "$GH_CACHE_IDS" ]; then
                    echo "No cache IDs left, end the loop."
                    break
                fi
                for GH_CACHE_ID in $GH_CACHE_IDS; do
                    echo "Delete Cache-ID: $GH_CACHE_ID"
                    curl \
                        -X DELETE \
                        -H "Accept: application/vnd.github.v3+json" \
                        -H "Authorization: token $GH_TOKEN" \
                        https://api.github.com/repos/$GH_ONWER/$GH_REPO/actions/caches/$GH_CACHE_ID
                done
                sleep 5
            done
          else
            echo "::warning::No recache selected - Skipping cache deletion ..."
          fi

  build_armhf:
    container:
      image: debian:trixie-slim
      options: --privileged
    strategy:
      fail-fast: false
      matrix:
        release: [bullseye, bookworm, trixie]
    runs-on: ubuntu-24.04-arm
    env:           
      PI_ARCH: armhf
    needs: clear_cache
    if: ${{ needs.clear_cache.result != 'failure' && github.repository == 'lizenzfass78851/pi-gen_imagepacks' && github.event.inputs.build_armhf != 'no' }}

    steps:

      - name: Generate pi images
        uses: LizenzFass78851/pi-gen_imagepacks/.github/actions/pi-gen@main
        with:
          pi_release: ${{ matrix.release }}
          pi_arch: ${{ env.PI_ARCH }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          compare_file0: ${{ env.COMPARE_FILE0 }}
          compare_file1: ${{ env.COMPARE_FILE1 }}
          repository: ${{ github.repository }}

  build_arm64:
    container:
      image: debian:trixie-slim
      options: --privileged
    strategy:
      fail-fast: false
      matrix:
        release: [bullseye, bookworm, trixie]
    runs-on: ubuntu-24.04-arm
    env:           
      PI_ARCH: arm64
    needs: clear_cache
    if: ${{ needs.clear_cache.result != 'failure' && github.repository == 'lizenzfass78851/pi-gen_imagepacks' && github.event.inputs.build_arm64 != 'no' }}

    steps:

      - name: Generate pi images
        uses: LizenzFass78851/pi-gen_imagepacks/.github/actions/pi-gen@main
        with:
          pi_release: ${{ matrix.release }}
          pi_arch: ${{ env.PI_ARCH }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          compare_file0: ${{ env.COMPARE_FILE0 }}
          compare_file1: ${{ env.COMPARE_FILE1 }}
          repository: ${{ github.repository }}
