name: generate_products

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/generate_products.yml'
      - '.github/actions/pi-gen/**'
      - '.github/actions/clear_cache/**'
  schedule:
    - cron: '34 14 */3 * 2'
  workflow_dispatch:
    inputs:
      build_armhf:
        description: 'Build armhf-Packages?'
        required: true
        options: [ 'yes', 'no' ]
        type: choice
        default: 'yes'
      build_arm64:
        description: 'Build arm64-Packages?'
        required: true
        options: [ 'yes', 'no' ]
        type: choice
        default: 'yes'
      recache:
        description: 'Delete Cache before Build?'
        required: false
        options: [ 'yes', 'no' ]
        type: choice
        default: 'no'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  COMPARE_FILE0: /tmp/.compare-0.txt
  COMPARE_FILE1: /tmp/.compare-1.txt

jobs:

  clear_cache:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'lizenzfass78851/pi-gen_imagepacks' }}
    permissions:
      actions: write
      contents: read
    steps:

      - name: clear_cache
        uses: LizenzFass78851/pi-gen_imagepacks/.github/actions/clear_cache@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_onwer: ${{ github.repository_owner }}
          repository_name: ${{ github.event.repository.name }}
          recache: ${{ github.event.inputs.recache }}

  build_armhf:
    container:
      image: debian:trixie-slim
      options: --privileged
    strategy:
      fail-fast: false
      matrix:
        release: [bullseye, bookworm, trixie]
    runs-on: ubuntu-24.04-arm
    env:           
      PI_ARCH: armhf
    needs: clear_cache
    if: ${{ !cancelled() && github.repository == 'lizenzfass78851/pi-gen_imagepacks' && needs.clear_cache.result != 'failure' && github.event.inputs.build_armhf != 'no' }}

    steps:

      - name: Generate pi images
        uses: LizenzFass78851/pi-gen_imagepacks/.github/actions/pi-gen@main
        with:
          pi_release: ${{ matrix.release }}
          pi_arch: ${{ env.PI_ARCH }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          compare_file0: ${{ env.COMPARE_FILE0 }}
          compare_file1: ${{ env.COMPARE_FILE1 }}
          repository: ${{ github.repository }}

  build_arm64:
    container:
      image: debian:trixie-slim
      options: --privileged
    strategy:
      fail-fast: false
      matrix:
        release: [bullseye, bookworm, trixie]
    runs-on: ubuntu-24.04-arm
    env:           
      PI_ARCH: arm64
    needs: clear_cache
    if: ${{ !cancelled() && github.repository == 'lizenzfass78851/pi-gen_imagepacks' && needs.clear_cache.result != 'failure' && github.event.inputs.build_arm64 != 'no' }}

    steps:

      - name: Generate pi images
        uses: LizenzFass78851/pi-gen_imagepacks/.github/actions/pi-gen@main
        with:
          pi_release: ${{ matrix.release }}
          pi_arch: ${{ env.PI_ARCH }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          compare_file0: ${{ env.COMPARE_FILE0 }}
          compare_file1: ${{ env.COMPARE_FILE1 }}
          repository: ${{ github.repository }}
