name: generate_products

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/generate_products.yml'
      - '.github/actions/pi-gen/**'
  schedule:
    - cron: '34 14 */3 * 2'
  workflow_dispatch:
    inputs:
      build_armhf:
        description: 'Build armhf-Packages?'
        required: true
        options: [ 'yes', 'no' ]
        type: choice
        default: 'yes'
      build_arm64:
        description: 'Build arm64-Packages?'
        required: true
        options: [ 'yes', 'no' ]
        type: choice
        default: 'yes'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
    
jobs:
  build_armhf:
    container:
      image: debian:trixie-slim
      options: --privileged
    strategy:
      fail-fast: false
      matrix:
        release: [buster, bullseye, bookworm, trixie]
    runs-on: ubuntu-24.04-arm
    env:           
      PI_ARCH: armhf
    if: ${{ github.repository == 'lizenzfass78851/pi-gen_imagepacks' && github.event.inputs.build_armhf != 'no' }}

    steps:

      - name: Generate pi images
        uses: LizenzFass78851/pi-gen_imagepacks/.github/actions/pi-gen@main
        with:
          pi_release: ${{ matrix.release }}
          pi_arch: ${{ env.PI_ARCH }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

  build_arm64:
    container:
      image: debian:trixie-slim
      options: --privileged
    strategy:
      fail-fast: false
      matrix:
        release: [bullseye, bookworm, trixie]
    runs-on: ubuntu-24.04-arm
    env:           
      PI_ARCH: arm64
    if: ${{ github.repository == 'lizenzfass78851/pi-gen_imagepacks' && github.event.inputs.build_arm64 != 'no' }}

    steps:

      - name: Generate pi images
        uses: LizenzFass78851/pi-gen_imagepacks/.github/actions/pi-gen@main
        with:
          pi_release: ${{ matrix.release }}
          pi_arch: ${{ env.PI_ARCH }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
